[package]
name = "lex_intent"
version = "0.1.0"
description = "LexIntent — Decentralized arbitration escrow for freelancers on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "lex_intent"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = []
default = []

[dependencies]
anchor-lang = "0.29.0"
solana-program = "1.18"

[profile.release]
overflow-checks = true
